### ISSUE TITLE
.jar download?

### ISSUE THREAD

**Issue by XDqrkneZ** [PikyCZ/NVault#2]
.jar download?

**Comment by PikyCZ** [comment]
download link: https://8-117971905-gh.circle-artifacts.com/0/tmp/circle-artifacts.0IH4JFM/NVault-0.1.jar
or https://circleci.com/gh/PikyCZ/NVault/8#artifacts/containers/0

**Comment by XDqrkneZ** [comment]
is the plugin usable atm?

**Comment by PikyCZ** [comment]
https://github.com/PikyCZ/NVault/blob/master/src/main/java/com/pikycz/nvaultapi/economy/Economy.java
